services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.app.rule=Host(`app.${DOMAIN_NAME}`)
      - traefik.http.routers.app.entrypoints=web,websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=mytlschallenge
      - traefik.http.services.app.loadbalancer.server.port=80
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage:ro
      - laravel-public-assets:/var/www/public/build:ro
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - laravel-production
      - proxy
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - laravel-production
      - proxy
  postgres:
    image: postgres:16
    user: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE:-app}
      - POSTGRES_USER=${POSTGRES_USERNAME:-laravel}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-laravel} -d ${POSTGRES_DATABASE:-app}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres-data-production:/var/lib/postgresql/data
    networks:
      - laravel-production
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - laravel-production
networks:
  laravel-production: 
  proxy:
    external: true
volumes:
  postgres-data-production: 
  laravel-storage-production: 
  laravel-public-assets: